package by.tarasiuk.ct.manager;

public enum DatabaseTableName {
    ACCOUNT_LOGIN,
    ACCOUNT_PASSWORD,
    ACCOUNT_EMAIL,
    ACCOUNT_REGISTRATION_DATE,
    ACCOUNT_PHONE_NUMBER,
    ACCOUNT_ADDRESS,
    ACCOUNT_ROLE_ID,
    ACCOUNT_STATUS_ID,

    ACCOUNT_ROLE_NAME,
    ACCOUNT_STATUS_NAME;
}
